---
title: "PCA"
author: "Matheus Machado de Almeida"
date: "26/09/2021"
output: html_document
---

```{r, include=F}
library(MVar.pt)
library(caret)
require(readr)

#carregar banco saude.csv

saude <- read_csv2("saude.CSV")

# remover variáveis qualitativas
saude2 <- saude[,-1]
```

### Utilizando prcomp() - Primerio método

```{r}
pca <- prcomp(saude2, scale = TRUE) 
print(pca)

## plot pc1 and pc2
plot(pca$x[,1], pca$x[,2])

# Construindo scree plot
screeplot(pca)
```

### Utilizando pacote MVar.pt - Segundo Método

```{r}
PC <- PCA(saude2, type=2) # Executa o PCA
Titles = c("Grafico das Observacoes", 
           "Circulo de Correlacoes")

Plot.PCA(PC, Titles)
```

```{r}
PC[["mtxAutvlr"]]
```

### PCA com train() - Terceiro Método

```{r}
# Criar amostras treino/teste
set.seed(100)
inTrain  <- createDataPartition(y = saude$Sexo, 
                                p = 0.75, 
                                list = F)
training <- saude[ inTrain,]
testing  <- saude[-inTrain,]

#####

ctrl <- trainControl(method = "boot", 
                     number = 30, 
                     preProcOptions = list(thresh = 0.95))
                   
modelFit_pca <- train(Sexo ~ .,
                      data = training, 
                      method = "knn",
                      preProcess = "pca", 
                      trControl = ctrl )

# Detalhes do treinamento
modelFit_pca

# Detalhes do pre-processamento
modelFit_pca$preProcess
```

### PCA com preProcess() - Quarto Método

```{r}
# padrao: thresh=0.95
pca <- preProcess(training, 
                  method = "pca")

training_pca <- predict(pca, 
                        training)

# alterando thresh
pca <- preProcess(training, 
                  method = "pca", 
                  thresh = 0.8); pca
```


